ALTER TABLE "Profile"
  DROP COLUMN IF EXISTS "lookingFor",
  DROP COLUMN IF EXISTS "offering";

ALTER TABLE "User"
  ADD COLUMN IF NOT EXISTS "connections" INTEGER[] NOT NULL DEFAULT ARRAY[]::INTEGER[];
